### ISSUE TITLE
HOT project template is not recognized

### ISSUE THREAD

**Issue by carokos** [ddsjoberg/starter#19]
When trying to create a new file from a specific project template, if the HOT template is chosen, there are only three options ("readme", "gitignore", "rproj"), despite more being written into the template code.

For example, if I want to create a new file from the HOT analysis template and use the code:
`bstfun::use_hot_analysis(filename = analysis1.Rmd)`
I get the following message/error: 
`√ Using 'Default Project Template' template`
`Error: Argument ``name=`` is not valid. Must be one of "readme", "gitignore", "rproj"`

If I try to specify the template file to use (i.e. analysis) using the code:
`bstfun::use_hot_file(name = "analysis", filename = "analysis1.Rmd")`
I get the following message/error:
`√ Using 'H.O.T. Project Template' template`
`x There was as error evaluating the the list defining the project template.
  If this is a template stored in the package, please file a GitHub Issue
  illustrating the error. If this is a personal template, review the vignette on
  creating a personal project template.`
`Error in template[[i]] : subscript out of bounds`

(I get this same error if I try to specify the HOT template)

**Comment by ddsjoberg** [comment]
this is occurring when `renv = FALSE` (which is TRUE for all `use_file_*()` functions), and the `rprofile` file evaluates to NULL. The length of the template list then changes when the rprofile element is set to NULL, resulting in a later out of bounds on the index error. The error is occurring in `eval_nested_lists()` internal function.

Potential solution:  The function contains a line `template[[i]] <- eval_if_call_or_expr(template[[i]], path, git, renv)`. If this was updated to something like `template[i] <- list(eval_if_call_or_expr(template[[i]], path, git, renv)) %>% setNames(template[i])` I think the NULL value will not change the length of the list. Perhaps, need to follow this up with a `purrr::compact()`?
