### ISSUE TITLE
ANSI escape codes showing on the website

### ISSUE THREAD

**Issue by IndrajeetPatil** [ddsjoberg/starter#25]
As seen here: https://www.danieldsjoberg.com/starter/articles/create_project.html

<img width="1232" alt="Screenshot 2022-04-20 at 20 29 15" src="https://user-images.githubusercontent.com/11330453/164298714-3541a765-de0d-425b-8c1a-53412450be8e.png">

**Comment by ddsjoberg** [comment]
aiya! 20 minutes after a cran submission too!

thanks, i'll take a look and see what is happening.

**Comment by ddsjoberg** [comment]
it's looking fine for me locally. maybe just need to rebuild the README and push an updated pkgdown

![image](https://user-images.githubusercontent.com/26774684/164300959-e4c61a1e-6c4c-4f6a-812c-32d10c789f21.png)

also check to see what is going on with the CRAN website...i'll check back in a few hours...
![image](https://user-images.githubusercontent.com/26774684/164301127-edf57473-e019-4102-abdb-b0b86ef34ac2.png)

**Comment by IndrajeetPatil** [comment]
Probably of help here: https://github.com/r-lib/pkgdown/issues/1843

**Comment by ddsjoberg** [comment]
@IndrajeetPatil you're a saint, thank you so much :)

**Comment by ddsjoberg** [comment]
oh no! I just went to add `collapse = TRUE` as the link indicates, but that is already set 😱 . Maybe is just build locally and push, it'll solve the problem for now.

**Comment by ddsjoberg** [comment]
i tried with the dev versions of both pkgdown and downlit, and no change.

I am just going to leave this open and worry about it another day 🤷🏼‍♂️

**Comment by IndrajeetPatil** [comment]
Oh, I know how to solve this issue.

Set `comment = "#>"` here:

https://github.com/ddsjoberg/starter/blob/a17fcad99cca904cc3bf20699c41cb312610133b/vignettes/create_project.Rmd#L42-L47

**Comment by ddsjoberg** [comment]
Thank you, thank you, thank you @IndrajeetPatil !

https://www.danieldsjoberg.com/starter/dev/articles/create_project.html
